import { FamilyNav } from "@/components/top-nav";
import { PageHeader } from "@/components/page-header";
import { Panel } from "@/components/panel";
import { Button } from "@/components/ui/button";

const DOCS = [
  { type: "PDF", name: "Pathology report.pdf", meta: "Uploaded May 14 · 2.4 MB · for C-2049", tone: "coral" },
  { type: "JPG", name: "Medication list photo.jpg", meta: "Uploaded May 14 · 880 KB · for C-2049", tone: "blue" },
  { type: "PDF", name: "Session summary — April 28.pdf", meta: "Generated by Caregma · May 2", tone: "teal" },
  { type: "PDF", name: "Questions for Dr. Chen.pdf", meta: "Generated by Caregma · May 2", tone: "teal" },
];

export default function DocumentsPage() {
  return (
    <>
      <FamilyNav />
      <div className="mx-auto max-w-[1100px] px-14 py-10 pb-20">
        <PageHeader
          title="Documents."
          subtitle="Files you've shared with your care guides, and summaries we've generated for you."
          actions={<Button>+ Upload file</Button>}
        />
        <Panel>
          {DOCS.map((d, i) => (
            <div key={d.name} className={`grid grid-cols-[48px_1fr_auto_auto] items-center gap-4 px-7 py-5 ${i < DOCS.length - 1 ? "border-b border-line-soft" : ""}`}>
              <div className={`flex h-10 w-10 items-center justify-center rounded-md text-[10px] font-semibold text-white ${d.tone === "coral" ? "bg-coral" : d.tone === "blue" ? "bg-[#1F4E7A]" : "bg-teal"}`}>
                {d.type}
              </div>
              <div>
                <div className="text-[15px] font-medium">{d.name}</div>
                <div className="text-[13px] text-ink-soft">{d.meta}</div>
              </div>
              <Button variant="ghost" size="sm">View</Button>
              <Button variant="ghost" size="sm">Download</Button>
            </div>
          ))}
        </Panel>
      </div>
    </>
  );
}
